### ISSUE TITLE
issue with special chars áéíóúç

### ISSUE THREAD

**Issue by pedroadaodev** [TimGeyssens/UIOMatic-Addons-Export#1]
Hi,

On the umbraco uiomatic reports I can see everything OK, but when I export and open the CSV file with Excell the special chars are incorrect. What can I do?

"RecomendaÃ§Ã£o de Amigo" must be "Recomendação de Amigo"
"Ana PatrÃ­-cia" must be "Ana Patrícia"

Thank in advance,
Pedro Adão

**Comment by ViGiLnT** [comment]
Hi @pedroadaodev!

I just had the same problem and forked @TimGeyssens repo so that I could fix it.
You can find the fix in my repo.

I've submitted the change by Pull Request to Tim.

**Comment by pedroadaodev** [comment]
Thank you so much @vigilnt :)
